name: Scheduled Sync

permissions:
  contents: read

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
    - name: "Checkout ${{ github.repository }}[${{ github.ref_name }}]"
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
      with:
        fetch-depth: 0
    -run: git remote -v
    -run: git status


#    - name: "Set git user details"
#      run: |
#        git config user.name "${{ github.actor }}"
#        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
