name: Scheduled Sync

permissions:
  contents: read

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  sync:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ref_name:
          - release/v1.28
          - release/v1.31
          - main
    steps:
    - id: appauth
      uses: envoyproxy/toolshed/gh-actions/appauth@actions-v0.2.35
      with:
        key: ${{ secrets.ENVOY_CI_UPDATE_BOT_KEY }}
        app_id: ${{ secrets.ENVOY_CI_UPDATE_APP_ID }}

    - name: "Checkout ${{ github.repository }}[${{ matrix.ref_name }}]"
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
      with:
        token: ${{ steps.appauth.outputs.token }}
        ref: ${{ matrix.ref_name }}
        fetch-depth: 0

    - name: "Set git user details"
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

    - run: ci/envoy-sync-receive.sh ${{ matrix.ref_name }}
      env:
          GH_TOKEN: ${{ steps.appauth.outputs.token }}
